version: 2.1
orbs:
  node: circleci/node@4.1
  slack: circleci/slack@3.4.2

jobs:
  deploy-to-test-site:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          app-dir: '~/project/v2'
      - run: cd ../ && git clone git@github.com:supertokens/supertokens-backend-website.git
      - run: cd v2 && npm run build
      - run: git config user.email "$EMAIL"
      - run: git config user.name "$NAME"
      - run: cd ../supertokens-backend-website && git add --all && git commit -m"docs changes" && git push && ./releaseDev.sh
      - slack/status

workflows:
  version: 2
  test:
    jobs:
      - deploy-to-test-site:
          context:
            - slack-notification
          filters:
            branches:
              only:
                - master
